[general] # normal stuff
live_config_reload = true

[window] # padding and bg-opacity
opacity = 0.6
blur = true
# -----------------------
padding.x = 10
padding.y = 10

        # jetbrains mono nerd font
[font]
size = 12.0

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

        # linux.toml colors
# Default colors
[colors.primary]
background = '#000000'
foreground = '#aaaaaa'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#aa5500'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#55ff55'
yellow  = '#ffff55'
blue    = '#5555ff'
magenta = '#ff55ff'
cyan    = '#55ffff'
white   = '#ffffff'
